// <auto-generated />
namespace EventsRegistration.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class firstmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201503231647297_firstmigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
